name: build image - test
on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
jobs:
  build-image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cri:
          - containerd
          - docker
          - cri-o
    steps:
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.7
        with:
          type: install
          pruneCRI: true
          sealosVersion: 4.2.0-alpha2
      - name: Remove containerd && docker
        uses: labring/sealos-action@v0.0.7
        with:
          type: prune
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto build image
        run: |
          sudo bash build-image.sh amd64
          cri=${{ matrix.cri }}
          case $cri in
          moby)
          cri=docker
          ;;
          cri-o)
          cri=crio
          ;;
          esac
          sudo sealos run "$(sudo sealos images | grep "dev-merge-$cri-k8s" | awk '{printf("%s:%s\n"),$1,$2}')" --single --debug
          {
            mkdir -p "$HOME/.kube"
            sudo cp /etc/kubernetes/admin.conf "$HOME/.kube/config"
            sudo chown "$(whoami)" "$HOME/.kube/config"
            kubectl get nodes --no-headers -oname | while read -r node; do kubectl get "$node" -o template='{{range .spec.taints}}{{.key}}{{"\n"}}{{end}}' | while read -r taint; do
              kubectl taint ${node/\// } "$taint"-
            done; done
            if ! bash waitRunning.sh 1 1; then
              echo "TIMEOUT(waitRunning)"
            fi
          }
