name: build image - push
on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
jobs:
  build-image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.7
        with:
          type: install
          pruneCRI: true
          sealosVersion: 4.2.0-alpha2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto build image
        run: |
          sudo bash build-image.sh ${{ matrix.arch }}
          sudo sealos login -u ${{ github.repository_owner }} -p ${{ secrets.G_REGISTRY_TOKEN }} ghcr.io
          sudo sealos images | grep ${{ github.repository_owner }}/dev-merge- | awk '{printf("%s:%s\n"),$1,$2}' | while IFS= read -r image; do
            echo "Pushing image: $image"
            sudo sealos push "$image"
          done
