name: build image - test
on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
jobs:
  build-image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cri:
          - containerd
          - docker
          - cri-o
    steps:
      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.7
        with:
          type: install
          pruneCRI: true
          sealosVersion: 4.2.0-alpha2
      - name: Remove containerd && docker
        uses: labring/sealos-action@v0.0.7
        with:
          type: prune
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto build image
        run: |
          sudo bash build-image.sh amd64 ghcr.io/labring-actions
          sudo sealos run ghcr.io/labring-actions/dev-merge-${{ matrix.cri }}-k8s:1.24.12-amd64 --single --debug
          {
            mkdir -p "$HOME/.kube"
            sudo cp /etc/kubernetes/admin.conf "$HOME/.kube/config"
            sudo chown "$(whoami)" "$HOME/.kube/config"
            kubectl get nodes --no-headers -oname | while read -r node; do kubectl get "$node" -o template='{{range .spec.taints}}{{.key}}{{"\n"}}{{end}}' | while read -r taint; do
            # shellcheck disable=SC2086
            kubectl taint ${node/\// } "$taint"-
            done; done
            if ! bash /tmp/waitRunning.sh 1 3; then
            echo "TIMEOUT(waitRunning)"
            fi
          }
          sudo sealos login -u labring-actions -p ${{ secrets.G_REGISTRY_TOKEN }} ghcr.io
          sudo images | grep ghcr.io/labring-actions/dev-merge- | while IFS= read -r image; do
            echo "Pushing image: $image"
            sudo sealos push "$image"
          done
